In [27]:
import pandas as pd

[Empty DataFrame]
0 Rows × 0 Columns
We have our first dataframe! But it's rather boring since it's empty. Fortunately, pandas gives us ways to fill dataframes with data.

In [28]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

Creating a dtaframe for:
Assign a color column.
Assign a radius column.
Show the result.

In [29]:
df = pd.DataFrame()
df['color'] = ['blue', 'red', 'green', 'orange', 'yellow']
df['radius'] = [2,4,5,6,7]
df

    color  radius
0    blue       2
1     red       4
2   green       5
3  orange       6
4  yellow       7

In [30]:
df['diameter'] = df['radius']*2
df

    color  radius  diameter
0    blue       2         4
1     red       4         8
2   green       5        10
3  orange       6        12
4  yellow       7        14

In [31]:
df1 = pd.DataFrame()
df1['Fruits'] = ['Apple', 'Orange', 'bananna']
df1['Price'] =  [50,60,70]
df1['Quantity in Kg'] = [1,2,3]
df1

    Fruits  Price  Quantity in Kg
0    Apple     50               1
1   Orange     60               2
2  bananna     70               3

In [32]:
df2 = pd.DataFrame()
df2['name'] = ['Ali', 'Ahmed', 'Sara', 'Zain', 'Ayesha']
df2['age'] = [20, 21, 19, 22, 20]
df2['marks'] = [85, 78, 92, 74, 88]
df2

     name  age  marks
0     Ali   20     85
1   Ahmed   21     78
2    Sara   19     92
3    Zain   22     74
4  Ayesha   20     88

In [33]:
# Another way (Best Practice)
data = {'color': ['blue', 'red', 'green', 'orange', 'yellow'],'radius': [2, 4, 5, 6, 7]}
df= pd.DataFrame(data)
df

    color  radius
0    blue       2
1     red       4
2   green       5
3  orange       6
4  yellow       7

### Summary calculations for columns

In [2]:
df['radius'].min()
# df['diameter'].max()
# df['radius'].mean()
# df1['Price'].sum()

NameError: name 'df' is not defined

### Columns as Series

In [ ]:
df['color']
# This returns the column as a Series.

0      blue
1       red
2     green
3    orange
4    yellow
Name: color, dtype: object

### Rows as Series

In [ ]:
# We can also access rows as series. For this we use the iloc[ ] accessor
# df.iloc['integer']
df.iloc[0]
df.iloc[1]
# last row
df.iloc[-1]

color       yellow
radius           7
Diameter        14
Name: 4, dtype: object

### Other parts of a dataframe
df.index contains the row labels.

df.columns contains the column names.

df.shape contains the size of the (rows, columns).

In [ ]:
# df.columns
# df1.columns
df2.columns

Index(['name', 'age', 'marks'], dtype='object')

In [ ]:
df.index
df1.index
df2.index

RangeIndex(start=0, stop=5, step=1)

In [35]:
df.shape

(5, 2)

In [37]:

# Rows
df.shape[0]
# columns
df.shape[1]

2

This dataset is about the layers of the Earth.

From the readme, we see that thickness is measured in kilometers.
Let's use the read_csv( ) function from the Pandas library to load 'earth-layers.csv' into a dataframe.

Instead of df, we'll use layers as a more descriptive variable name.

In [44]:
layers = pd.read_csv("./data/earth_layers.csv")
layers

        layer  thickness
0       crust         40
1      mantle       2900
2  outer core       2200
3  inner core       1230