### How to do Skimming of the data

# What EDA really is (not the buzzword version)

Exploratory Data Analysis (EDA) is the process of understanding reality hidden inside raw data before you touch models, dashboards, or decisions.
Clients don’t pay for algorithms.They pay for clarity, confidence, and correct decisions.
EDA is how you get there.

# The Purpose of EDA (Client-Centric View)

1-To Understand What the Data Actually Represents

Clients often think they know their data.
They usually don’t.

Example:
Column: temperature
Client says: “This is daily temperature”\
EDA reveals:\
Some values are in °C, some in °F
Some are sensor errors (-999, 0)
Some days are missing

👉 Without EDA, your model is garbage in → garbage out.
<br>
EDA answers:\
1.What does each column really mean?\
2.What unit, scale, and range does it live in?\
3.Is this column even usable?

2- To Detect Data Quality Problems\
In real-world projects:
70–80% of effort is data cleaning, Clients rarely mention problems upfront\ 
EDA helps you find:
Missing values,
Duplicates,
Outliers,
Inconsistent categories,
Impossible values

Example (ecological data):\
Species count = -5,
Rainfall = 5000 mm/day,
Population = 0 for an inhabited region,\
These aren’t “small issues.” They change conclusions.

👉 Clients love EDA because it protects them from wrong decisions.

In [74]:
# import libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import ydata_profiling as yd
# from skimpy import skim

In [75]:
df_GPS = pd.read_csv("./data/googleplaystore.csv")

In [76]:
df_GPS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  int64
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10841 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10839 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 1.1+ MB

In [77]:
df_GPS.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [78]:
df_GPS.describe()

            Rating       Reviews
count  9367.000000  1.084100e+04
mean      4.191513  4.441119e+05
std       0.515735  2.927629e+06
min       1.000000  0.000000e+00
25%       4.000000  3.800000e+01
50%       4.300000  2.094000e+03
75%       4.500000  5.476800e+04
max       5.000000  7.815831e+07

In [79]:
# Run automatic EDA anlaysis
profile = yd.ProfileReport(df_GPS)
profile.to_file(output_file='./ouputs/04_clean_ydata_kaggle_googleapp.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 13/13 [00:01<00:00, 11.82it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [80]:
df_GPS.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
8057,CX Carrier Lite,BUSINESS,NaN,0,68M,10+,Free,0,Everyone,Business,"June 11, 2018",1.0,4.0 and up
1673,PAC-MAN,GAME,4.2,685981,37M,"100,000,000+",Free,0,Everyone,Arcade,"May 15, 2018",6.6.3,4.1 and up
2487,Anthem BC Anywhere,MEDICAL,2.6,496,24M,"100,000+",Free,0,Everyone,Medical,"July 27, 2018",8.0.226,4.4 and up
10568,Crazy Freekick,SPORTS,3.9,47688,17M,"5,000,000+",Free,0,Everyone,Sports,"May 18, 2016",1.0.15,2.3 and up
2509,MedStar eVisit,MEDICAL,4.5,20,40M,"5,000+",Free,0,Everyone,Medical,"April 10, 2018",10.4.1.000_00,4.0.3 and up
3239,Cache Cleaner-DU Speed Booster (booster & clea...,TOOLS,4.5,12759663,15M,"100,000,000+",Free,0,Everyone,Tools,"July 25, 2018",3.1.2,4.0 and up
8307,LINE Camera - Photo editor,PHOTOGRAPHY,4.3,1517395,Varies with device,"100,000,000+",Free,0,Everyone,Photography,"March 6, 2018",Varies with device,Varies with device
9842,"Groupon - Shop Deals, Discounts & Coupons",SHOPPING,4.6,1371082,Varies with device,"50,000,000+",Free,0,Teen,Shopping,"August 3, 2018",Varies with device,Varies with device
3478,ASUS Calling Screen,PRODUCTIVITY,4.2,102451,Varies with device,"10,000,000+",Free,0,Everyone,Productivity,"March 15, 2018",Varies with device,Varies with device
1499,Wall Decorating Ideas,HOUSE_AND_HOME,3.9,6631,5.5M,"1,000,000+",Free,0,Everyone,House & Home,"March 11, 2015",1.5,3.0 and up

In [81]:
df_GPS['Size'].unique()
df_GPS['Size'].nunique()

461

In [82]:
df_GPS['Size'].value_counts()

Size
Varies with device    1695
11M                    198
12M                    196
14M                    194
13M                    191
                      ...
253k                     1
992k                     1
658k                     1
73k                      1
246k                     1
Name: count, Length: 461, dtype: int64

In [83]:
df_GPS['Installs'].value_counts()

Installs
1,000,000+        1579
10,000,000+       1252
100,000+          1169
10,000+           1054
1,000+             908
5,000,000+         752
100+               719
500,000+           539
50,000+            479
5,000+             477
100,000,000+       409
10+                386
500+               330
50,000,000+        289
50+                205
5+                  82
500,000,000+        72
1+                  67
1,000,000,000+      58
0+                  14
0                    1
Name: count, dtype: int64

In [84]:
# If the column is already clean (no text)
# df_GPS['column_name'] = df_GPS['column_name'].astype(int)

# OR
#df_GPS['column_name'] = df_GPS['column_name'].astype(float)

# # converting column from object to numeric 
# pd.to_numeric(..., errors='coerce') sirf already numeric-looking strings ko convert karta hai
# Agar string mein letters (M/k) hain, wo NaN ban jati hain

df_GPS['Installs'] = pd.to_numeric(df_GPS['Installs'], errors='coerce')
df_GPS.dtypes

App                object
Category           object
Rating            float64
Reviews             int64
Size               object
Installs          float64
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [85]:
df_GPS = pd.read_csv('./data/googleplaystore.csv', dtype={'Size': str})

In [96]:
# Ensure Size is string
# Series object ke paas .strip() method nahi hota. .strip() sirf Python string object ke liye hota hai.
df_GPS['Size'] = df_GPS['Size'].astype(str).str.strip()

In [97]:
# Replace 'Varies with device'
df_GPS['Size'] = df_GPS['Size'].replace('Varies with device', np.nan)

In [98]:
# Extract numbers Basically, text me se numeric value extract karna.
size_num = df_GPS['Size'].str.extract(r'([\d.]+)')[0]

# .str.extract() → Pandas string method hai jo regular expression (regex) use karta hai aur string se pattern extract karta hai.
# r'([\d.]+)' → ye regex pattern hai.
# \d → kisi bhi digit ko match karta hai (0–9)
# . → dot . ko match karta hai (decimal numbers ke liye)
# [\d.]+ → ek ya zyada digits ya dots ko match karega
# () → parentheses ka matlab hai capture group, matlab ye wahi part return karega jo parentheses ke andar match hua

# ek line say dono tasks
# size_num = df_GPS['Size'].str.extract(r'([\d.]+)')[0].astype(float)

In [ ]:
# Detect units
is_mb = df_GPS['Size'].str.contains('M', na=False)
is_kb = df_GPS['Size'].str.contains('k', na=False)

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Size, Length: 10841, dtype: bool

In [90]:
# Convert to MB
df_GPS['Size'] = np.where(
    is_mb,
    size_num.astype(float),
    np.where(
        is_kb,
        size_num.astype(float) / 1024,
        np.nan
    )
)

In [91]:
df_GPS['Size'].value_counts()

Size
11.000000    198
12.000000    196
14.000000    194
13.000000    191
15.000000    184
            ...
0.539062       1
0.864258       1
0.996094       1
0.568359       1
0.604492       1
Name: count, Length: 459, dtype: int64

In [92]:
df_GPS['Size'].isnull()

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839     True
10840    False
Name: Size, Length: 10841, dtype: bool

In [ ]:
# If column contains symbols (real-world case) e.g "1,000+", "10+", "$4.99"

df_GPS['Installs'] = (
    df_GPS['Installs']
    # .str.replace('$', '', regex=False)
    .str.replace('+', '', regex=False)
    # .str.replace(',','',  regex=False)
    .astype(int)
)